### ISSUE TITLE
'argument can not have class as its default value' is too strict

### ISSUE THREAD

**Issue by thedrow** [dry-python/dependencies#127]
I have a class which can be customized using a strategy.
I have declared it as such:
```python
@attr.s(auto_attribs=True, cmp=False)
class Blueprint:
    """A directed acyclic graph of Bootsteps."""

    _steps: DiGraph = attr.ib(default=attr.NOTHING)
    name: str = "Blueprint"
    state: BlueprintState = attr.ib(default=BlueprintState.INITIALIZED, init=False)
    order_execution_strategy: Iterator = ExecutionOrder
```

I'm initializing it on demand without using the container since there's no need for that.
I'd like to pass a type to the `order_execution_strategy` argument.

Currently, that's not possible. What's worse is that you cannot use a type as a default value for some reason.

**Comment by proofit404** [comment]
There is a reason for such kind of behavior.

Let's suppose you didn't include `order_execution_strategy` into `Injector` subclass.

When you build a `Blueprint` using this `Injector` you'll have a class stored in the strategy attribute.

Let's suppose you do include `order_execution_strategy` into `Injector` subclass.

When you build a `Blueprint` using the second `Injector` variant you'll have an instance of the class stored in the strategy attribute.

This is inconsistent behavior we are fighting with this restriction.

If you want to inject a class or a type into `Blueprint` you should name `__init__` argument ending with `_class`. I.e. `order_execution_strategy_class`. This will prevent it from the instantiation and will check that you actually put a class into `Injector` scope.

If you have suggestions about this approach, feel free to open another issue. For example, how we can improve this approach?

I hope that helps.

Best regards,
Artem.

**Comment by thedrow** [comment]
You need to document it.
The exception message itself should explain how to fix this problem as well.

**Comment by proofit404** [comment]
It is already documented: https://dependencies.readthedocs.io/en/latest/usage/#injection-rules

I agree we need to make a clear error message with it.

Thanks!
