### ISSUE TITLE
Support cached-property package.

### ISSUE THREAD

**Issue by proofit404** [dry-python/dependencies#187]
https://pypi.org/project/cached-property/

This should help us to avoid connection pool creation on each request.

**Comment by thedrow** [comment]
You should also support [`cached_property`](https://docs.python.org/3/library/functools.html#functools.cached_property) from Python 3.8+.

**Comment by proofit404** [comment]
For sure! Thanks for the info 🤗

**Comment by proofit404** [comment]
In the case of the dependency injection, this feature would be a singleton. I want singletons to be as hard as it should be.

If the users will need it, they will implement it in their own way.

**Comment by mt3925** [comment]
> In the case of the dependency injection, this feature would be a singleton. I want singletons to be as hard as it should be.
> 
> If the users will need it, they will implement it in their own way.

I don’t quite understand the meaning of this sentence, would you mind explaining it in detail?

**Comment by proofit404** [comment]
A singleton is something that should be instantiated once, but constructor is called every time you need an instance.

```python
from cached_property import cached_property
from dependencies import Injector


class Container(Injector):
    a = 1
    b = 2

    @cached_property
    def foo(self):
        pass
```
In this case, `foo` could be considered a singleton. But, it's a third-party dependency, which requires additional work. And it requires `self` argument which is not exist in dependencies injector.

An alternative approach would be implemented as part of the https://github.com/proofit404/dependencies/issues/299
