### ISSUE TITLE
Maybe mention in the docs that dependencies Django contrib module is deprecated?

### ISSUE THREAD

**Issue by josh-stableprice** [dry-python/dependencies#249]
I found out that this may be the case via the accompanying https://github.com/dry-python/bookshelf examples. Specifically in this commit https://github.com/dry-python/bookshelf/commit/a1f9f70c4af8c4c6b5479b0f3ce410697969bbb3 you mention that this module was deprecated 2 months ago. Is this still the case?

**Comment by proofit404** [comment]
Hi, thank you for the issue!

Yes, the `contrib` package is deprecated. If you can submit a pull request to mention it, please do.

When I'll be able to finish https://github.com/dry-python/dependencies/pull/193 the next major release will land. The only thing left to do is `doctest` failure.

Have a good day :tada: 

Best regards, 
Artem.
