### ISSUE TITLE
Add value decorator.

### ISSUE THREAD

**Issue by proofit404** [dry-python/dependencies#26]

**Comment by proofit404** [comment]
Blocked by #38

**Comment by proofit404** [comment]
### Coroutines

```python
import asincio
import aiopg

class App:
    def __init__(self, db):
        self.db = db

class Container(Injector):
    app = App

    loop = asyncio.get_event_loop()
    dsn = 'dbname=aiopg user=aiopg password=passwd host=127.0.0.1'

    @value
    async def db(dns):
        return await aiopg.create_pool(dsn)

assert isinstance(Container.app.db, <postgres db pool class>)
```

Moved from https://github.com/dry-python/dependencies/issues/34

**Comment by thedrow** [comment]
Is this documented or implemented somewhere?
I don't see anything about it in the code.

**Comment by proofit404** [comment]
Hi!

The `value` decorator is implemented in the master.

https://github.com/dry-python/dependencies/blob/master/src/dependencies/_value.py

But this was not released yet.

Regards, Artem.
