### ISSUE TITLE
Mention integration with Celery in the docs

### ISSUE THREAD

**Issue by thedrow** [dry-python/dependencies#33]
Hi,
Celery core contributor here.

Thank's for the celery integration.
Would you mind if we documented this integration in our documentation?
Can you issue a PR?

Thanks :)

**Comment by proofit404** [comment]
Hi, if I understand correctly you want to include notes about dependencies in the Celery official documentation. Is this correct? If so, thanks for the generous offer! I'll take it.

Let me explain the current state and the roadmap of dependencies package.

The whole `contrib` system isn't released yet.

The only things I have to do `model_view_set` decorator for rest_framework contrib and the whole documentation part for all contribs, operation decorator and Package proxy.

The last part can be done in parallel with PR to the Celery docs.

Hopefully I'll be able to wrap it up in next few weeks.

Regards, Artem.

**Comment by thedrow** [comment]
Yes this is correct.
I was actually planning to use this library for Celery 5 but there are a lot of improvements to be done in order for this package to be stable.

**Comment by proofit404** [comment]
0.15 is out! We can start to work on docs PR.
