### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by thedrow** [dry-python/dependencies#90]
It's been quite a while since the last version was released.
What's missing and how can I help?

**Comment by proofit404** [comment]
Hi!

Yeh, I need to confess that lack of clean roadmap and periodic releases is my personal failure. I'm bad at working on the project in small iterative steps and all this looks like one huge hackathon.

I'll try to follow the protected master branch with PR only approach from the talk by Hynek https://www.youtube.com/watch?v=9G2s1TN9QQY

I guess it should prevent a situation like this one in the future.

There are a lot of things to do before we can make a new release happen.

* setup new GitHub project board with issues
* complete flask framework contrib
* complete all issues related to django and rest framework contrib (there are some issues not published yet)
* nearly rework documentation
* fix mypy build

As you can see there is a lot of things left to do...

We are trying to get some funding exactly for this task from companies which are using the current master branch at work.

Hopefully, it'll happen in a few months.

Thanks for your patience.

Regards, Artem.

**Comment by thedrow** [comment]
I don't have a use for the contrib package.
Maybe we should separate the release process of the core library from the contrib package?

**Comment by thedrow** [comment]
Right so this became more urgent since I need the `@value` decorator.

**Comment by proofit404** [comment]
Hi Omer,

Thanks for your patience!

If we have some customer, who can support the development of this release, everything will be faster.

For now, I'm working on exactly the same issue in the `stories` project. https://github.com/dry-python/stories/pull/187

If you or your colleagues can solve some issues blocking new release this will be great!

I'll try to set up the GitHub Project Board for next release during this week.

So we'll be able to collaborate easily with a clear scope.

Regards, 
Artem.

**Comment by thedrow** [comment]
So right now we need to complete the contrib and docs?

**Comment by proofit404** [comment]
Hi Omer,

I've created the project for the next release: https://github.com/orgs/dry-python/projects/5

So we can track the progress there.

I've got a new job a few weeks ago so my time is very limited.

I understand that you want to build on top of the dependencies. The Celery project is the main goal if I understand correctly. And we are really interested to contribute to it.

If you could share your timelines (privately if necessary) we could adjust the scope of our work.

Hope that helps.

Best regards,
Artem.

**Comment by proofit404** [comment]
Fixed by https://github.com/dry-python/dependencies/pull/195
